name: 'All Github Actions lives matter'
description: 'Keeps Github Actions alive'
inputs:
  user-name:
    description: 'Your Github username'
    required: true
  user-email: 
    description: 'Your email used for Github account'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.user-name }}
    - ${{ inputs.user-email }}
